# Site settings
title: John Speck Creative
email: callme@johnspeckcreative.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frymaster.github.io" # the base hostname & protocol for your site
port: 4001
# permalink: article/:title
